export const defaultPermissions = [
  {
    id: "user-create",
    name: "user:create",
    resource: "user",
    action: "create",
    description: "Create new users",
  },
  {
    id: "user-read",
    name: "user:read",
    resource: "user",
    action: "read",
    description: "View users",
  },
  {
    id: "user-update",
    name: "user:update",
    resource: "user",
    action: "update",
    description: "Update users",
  },
  {
    id: "user-delete",
    name: "user:delete",
    resource: "user",
    action: "delete",
    description: "Delete users",
  },

  {
    id: "server-create",
    name: "server:create",
    resource: "server",
    action: "create",
    description: "Create new servers",
  },
  {
    id: "server-read",
    name: "server:read",
    resource: "server",
    action: "read",
    description: "View servers",
  },
  {
    id: "server-update",
    name: "server:update",
    resource: "server",
    action: "update",
    description: "Update server settings",
  },
  {
    id: "server-delete",
    name: "server:delete",
    resource: "server",
    action: "delete",
    description: "Delete servers",
  },
  {
    id: "server-start",
    name: "server:start",
    resource: "server",
    action: "start",
    description: "Start servers",
  },
  {
    id: "server-stop",
    name: "server:stop",
    resource: "server",
    action: "stop",
    description: "Stop servers",
  },
  {
    id: "server-restart",
    name: "server:restart",
    resource: "server",
    action: "restart",
    description: "Restart servers",
  },
  {
    id: "server-console",
    name: "server:console",
    resource: "server",
    action: "console",
    description: "Access server console",
  },
  {
    id: "server-logs",
    name: "server:logs",
    resource: "server",
    action: "logs",
    description: "View server logs",
  },
];
